name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - jallen-dev
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What operating system are you using?
      options:
        - Android
        - iOS
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true
  - type: input
    id: extra-platform-details
    attributes:
      label: "Optional: extra platform/browser details"
      description: If you selected 'Other' for either of the above, please provide more details here.
      placeholder: "e.g. 'Ubuntu 20.04' or 'Firefox 89'"
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe what happened
      description: Please describe in as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
